# Generated by Django 5.2.4 on 2025-09-18 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("rivals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="fpl_id",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="manager_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rivals.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="team_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
