# Generated by Django 5.2.4 on 2025-09-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_active_user_fpl_id_user_manager_name_user_team_and_more",
        ),
        ("rivals", "0003_alter_trackedteam_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="rivals.team",
            ),
        ),
    ]
