# Generated by Django 5.2.4 on 2026-01-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_team"),
        ("rivals", "0004_alter_gameweekdata_bench_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mini_leagues",
            field=models.ManyToManyField(
                related_name="users",
                through="rivals.UserMiniLeague",
                to="rivals.minileague",
            ),
        ),
    ]
