# Generated by Django 5.2.4 on 2025-09-18 08:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fpl_league_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "league_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scoring_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("has_cup", models.BooleanField(default=False)),
                (
                    "admin_entry_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_event", models.IntegerField(blank=True, null=True)),
                ("entry_can_leave", models.BooleanField(default=False)),
                ("entry_can_admin", models.BooleanField(default=False)),
                ("entry_can_invite", models.BooleanField(default=False)),
                ("rank_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fpl_id", models.IntegerField(unique=True)),
                ("web_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "second_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("element_type", models.IntegerField()),
                ("team_id", models.IntegerField(blank=True, null=True)),
                ("now_cost", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "selected_by_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "form",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                ("can_transact", models.BooleanField(default=True)),
                ("removed", models.BooleanField(default=False)),
                ("news", models.TextField(blank=True, null=True)),
                ("news_added", models.DateTimeField(blank=True, null=True)),
                ("minutes", models.IntegerField(default=0)),
                ("goals_scored", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("clean_sheets", models.IntegerField(default=0)),
                ("goals_conceded", models.IntegerField(default=0)),
                ("yellow_cards", models.IntegerField(default=0)),
                ("red_cards", models.IntegerField(default=0)),
                ("bonus", models.IntegerField(default=0)),
                (
                    "expected_goals",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=5
                    ),
                ),
                (
                    "expected_assists",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=5
                    ),
                ),
                (
                    "ict_index",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fpl_id"], name="rivals_play_fpl_id_40f12b_idx"
                    ),
                    models.Index(
                        fields=["element_type"], name="rivals_play_element_1e3b94_idx"
                    ),
                    models.Index(
                        fields=["element_type", "total_points"],
                        name="rivals_play_element_040d33_idx",
                    ),
                    models.Index(
                        fields=["team_id"], name="rivals_play_team_id_0f6f79_idx"
                    ),
                    models.Index(
                        fields=["web_name"], name="rivals_play_web_nam_2dc3de_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fpl_team_id", models.CharField(max_length=255, unique=True)),
                ("team_name", models.CharField(max_length=255)),
                ("manager_name", models.CharField(max_length=255)),
                ("current_total_points", models.IntegerField(default=0)),
                ("current_overall_rank", models.IntegerField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(null=True)),
                ("bank", models.IntegerField(default=0)),
                ("value", models.IntegerField(default=1000)),
                ("total_transfers", models.IntegerField(default=0)),
                ("fpl_favourite_team_id", models.IntegerField(null=True)),
                ("years_active", models.IntegerField(null=True)),
                ("started_event", models.IntegerField(null=True)),
                ("current_event_points", models.IntegerField(default=0)),
                ("current_event_rank", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fpl_team_id"], name="rivals_team_fpl_tea_2c51df_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MiniLeagueTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_rank", models.IntegerField()),
                ("previous_rank", models.IntegerField(blank=True, null=True)),
                ("total_points", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mini_league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rivals.minileague",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rivals.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="minileague",
            name="teams",
            field=models.ManyToManyField(
                related_name="mini_leagues",
                through="rivals.MiniLeagueTeam",
                to="rivals.team",
            ),
        ),
        migrations.CreateModel(
            name="GameweekData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameweek", models.IntegerField()),
                ("points", models.IntegerField()),
                ("total_points", models.IntegerField()),
                ("bench_points", models.IntegerField()),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("rank_sort", models.IntegerField(blank=True, null=True)),
                ("event_transfers", models.IntegerField(default=0)),
                ("event_transfers_cost", models.IntegerField(default=0)),
                (
                    "captain_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vice_captain_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("chip_played", models.BooleanField(default=False)),
                ("chip_name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rivals.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackedTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rivals.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameweek", models.IntegerField()),
                ("player_in_name", models.CharField(max_length=255)),
                ("player_out_name", models.CharField(max_length=255)),
                (
                    "player_in_cost",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "player_out_cost",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("transfer_time", models.DateTimeField(blank=True, null=True)),
                ("point_cost", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_in",
                        to="rivals.player",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to="rivals.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rivals.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMiniLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mini_league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rivals.minileague",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SquadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameweek", models.IntegerField()),
                ("player_fpl_id", models.IntegerField()),
                ("position", models.IntegerField()),
                ("multiplier", models.IntegerField()),
                ("is_captain", models.BooleanField(default=False)),
                ("is_vice_captain", models.BooleanField(default=False)),
                ("element_type", models.IntegerField()),
                ("player_name", models.CharField(max_length=255)),
                ("player_cost", models.IntegerField()),
                (
                    "form",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "expected_goals",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "expected_assists",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "selected_by_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_points_at_time", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rivals.team"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team", "gameweek"],
                        name="rivals_squa_team_id_a71b13_idx",
                    ),
                    models.Index(
                        fields=["player_fpl_id"], name="rivals_squa_player__f661f2_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="minileagueteam",
            index=models.Index(
                fields=["mini_league"], name="rivals_mini_mini_le_59f8fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="minileagueteam",
            index=models.Index(fields=["team"], name="rivals_mini_team_id_deb234_idx"),
        ),
        migrations.AddIndex(
            model_name="minileague",
            index=models.Index(
                fields=["fpl_league_id"], name="rivals_mini_fpl_lea_5529e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="minileague",
            index=models.Index(
                fields=["admin_entry_id"], name="rivals_mini_admin_e_1fb871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="minileague",
            index=models.Index(
                fields=["league_type"], name="rivals_mini_league__23f5a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gameweekdata",
            index=models.Index(fields=["team"], name="rivals_game_team_id_200654_idx"),
        ),
        migrations.AddIndex(
            model_name="gameweekdata",
            index=models.Index(
                fields=["gameweek"], name="rivals_game_gamewee_0e0a3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackedteam",
            index=models.Index(fields=["user"], name="rivals_trac_user_id_50ec1d_idx"),
        ),
        migrations.AddIndex(
            model_name="trackedteam",
            index=models.Index(fields=["team"], name="rivals_trac_team_id_5ef06b_idx"),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(fields=["team"], name="rivals_tran_team_id_56c49d_idx"),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["team", "gameweek"], name="rivals_tran_team_id_e466fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["gameweek", "point_cost"], name="rivals_tran_gamewee_e48f8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["player_in"], name="rivals_tran_player__2adaa9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["player_out"], name="rivals_tran_player__2f5d16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["point_cost"], name="rivals_tran_point_c_f62221_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userminileague",
            index=models.Index(fields=["user"], name="rivals_user_user_id_e10344_idx"),
        ),
        migrations.AddIndex(
            model_name="userminileague",
            index=models.Index(
                fields=["mini_league"], name="rivals_user_mini_le_ed88d6_idx"
            ),
        ),
    ]
