# Generated by Django 5.2.4 on 2025-09-18 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rivals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameweekdata",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gameweek_data",
                to="rivals.team",
            ),
        ),
        migrations.AlterField(
            model_name="minileagueteam",
            name="mini_league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mini_league_teams",
                to="rivals.minileague",
            ),
        ),
        migrations.AlterField(
            model_name="minileagueteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mini_league_teams",
                to="rivals.team",
            ),
        ),
        migrations.AlterField(
            model_name="squadhistory",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="squad_histories",
                to="rivals.team",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="rivals.team",
            ),
        ),
    ]
