# Generated by Django 5.2.4 on 2025-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rivals", "0003_alter_trackedteam_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameweekdata",
            name="bench_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gameweekdata",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gameweekdata",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
