# Generated by Django 5.2.4 on 2026-02-01 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rivals", "0004_alter_gameweekdata_bench_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My Plan", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_plans",
                        to="rivals.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PlannedTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameweek", models.IntegerField()),
                ("order", models.IntegerField(default=0)),
                (
                    "player_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_transfers_in",
                        to="rivals.player",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_transfers_out",
                        to="rivals.player",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="rivals.transferplan",
                    ),
                ),
            ],
            options={
                "ordering": ["gameweek", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="transferplan",
            index=models.Index(
                fields=["user", "is_active"], name="rivals_tran_user_id_f59c07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannedtransfer",
            index=models.Index(
                fields=["plan", "gameweek"], name="rivals_plan_plan_id_0a9f8e_idx"
            ),
        ),
    ]
